language: python
matrix:
    include:
        - python: 3.6
          dist: trusty
          sudo: false
        - python: 3.7
          dist: xenial
          sudo: true
          after_script: make sonar

addons:
    sonarcloud:
        organization: lightswitch05
        token:
            secure: KOv9+N5rhDqCtZoGXr3D99509MxCnMIb19NNdyotp1b8Rda+pKdfs+WaFyQFSXEyuhee5pyUPUuB4048CTqCoaV2MkgbKx56e4JAhX2mz4S1J20DN1UALdLfW40VpRGEtnRsDuJFs53oKmiojsrTJ5czD+5b0Ijf+5dBR34P05sUmSUXjbMqexhgxHX++X4A1P775QR9Y47kUEDS9KTXgERblDNliuxtNftVBjR62VLIJ+pLbQPuy9k0ZsJK8My9eyZiddspBWuMf96fHxEeume3KM/L80jXVQ/6FJAx2WJPuTY8oPQW5BW7VrZrhll0PLrcF1Px1bPFXlQS8JeVe0EzMVuwgZlkvmTpXbNIjrhR94pnjFmHuYSWqKbH6vnG9l/Ip0RmiMNrzTzyT0RZ2+FauT2b4tov3y/GNvlYz9t+CzmY9RSzZxBGOs2Rh22dnIc7d3dc+gtpvy+tSRDI9iYQW/FDqRC56+PM8h/g6cotDwhTzz2jFh/s11XjriF8qP6pZsPWz71wWKLW8s8rSFhnrVdxHpbgle12Pv6bR+ZWInovdkBVJ27B7N+lsW7fP2VCWmGqlMnC5xhWJrCQVaEKbVX6pWjpLSgAoe1iUZPO+ESmfKJxtQVpybj/ciNfs3o2vKg/190VULFkjm/IEendxIRB1H6gNi2FjtmdpvE=
install:
    - make setup
script:
    - make test-travis

git:
    depth: false
